// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wiazpjgccgexlbtprucl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpYXpwamdjY2dleGxidHBydWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzU0NzcsImV4cCI6MjA2OTYxMTQ3N30.8iC1xPScNxNkwnU4jRKDkKaZ3TTbDINc3ndqMS3jZ2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});